(function(){
  'use strict';
  const UNIT_OPTIONS=['Bottle','Packet','Box','Vial','Tube','Ampoule','Can','Bag','Drum','Piece','Set','Other'];
  const $=id=>document.getElementById(id);
  const state={inventory:[],products:[],billLines:[],staff:null};
  const els={loginView:$('login-view'),dashboard:$('dashboard-view'),loginForm:$('login-form'),loginMsg:$('login-message'),logout:$('logout'),logoutTop:$('logout-top'),staffEmail:$('staff-email'),staffAvatar:$('staff-avatar'),invBody:$('inventory-table-body'),invSearch:$('inventory-search'),invMsg:$('inventory-message'),invCount:$('inventory-count'),invEmpty:$('inventory-empty'),pickerSearch:$('product-picker-search'),picker:$('product-picker'),pickerCount:$('picker-count'),dialog:$('inventory-dialog'),form:$('inventory-form'),unit:$('edit-unit'),billingMsg:$('billing-message'),billSelect:$('bill-product-select'),billQty:$('bill-qty'),billBody:$('bill-lines-body')};
  function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
  function message(el,text,type=''){el.textContent=text||'';el.hidden=!text;el.className='staff-message'+(type?' '+type:'');}
  async function api(path,options={}){const r=await fetch(path,{...options,headers:{'content-type':'application/json',...(options.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Request failed');return data;}
  async function me(){try{return (await api('/api/auth/me')).staff}catch{return null}}
  async function loadProducts(){if(state.products.length)return;const r=await fetch('data/products.json',{cache:'no-store'});state.products=await r.json();renderPicker();}
  async function loadInventory(){const q=els.invSearch.value.trim();const d=await api('/api/inventory'+(q?'?q='+encodeURIComponent(q):''));state.inventory=d.items||[];renderInventory();populateBillingProducts();await loadSummary();}
  async function loadSummary(){const d=await api('/api/summary');$('metric-skus').textContent=Number(d.summary.skus).toLocaleString('en-IN');$('metric-total').textContent=Number(d.summary.totalUnits).toLocaleString('en-IN');$('metric-grades').textContent=Number(d.summary.grades).toLocaleString('en-IN');$('unit-summary').innerHTML=(d.summary.byUnit||[]).map(x=>`<div class="unit-chip"><span>${esc(x.unit)}</span><strong>${Number(x.quantity).toLocaleString('en-IN')}</strong></div>`).join('')||'<div class="muted">No inventory yet.</div>';}
  async function loadBills(){const d=await api('/api/bills/recent');$('recent-bills-body').innerHTML=(d.bills||[]).map(b=>`<tr><td><strong>${esc(b.invoice_no)}</strong></td><td>${esc(b.customer_name||'—')}</td><td>${esc(b.total_units)}</td><td>${esc(b.staff_email)}</td><td>${new Date(b.created_at.replace(' ','T')+'Z').toLocaleString('en-IN')}</td></tr>`).join('');}
  function renderInventory(){const q=els.invSearch.value.trim().toLowerCase();const rows=state.inventory.filter(r=>!q||[r.sku,r.product_name,r.cas_number,r.grade].join(' ').toLowerCase().includes(q));els.invCount.textContent=`${rows.length.toLocaleString('en-IN')} item${rows.length===1?'':'s'}`;els.invEmpty.hidden=rows.length>0;els.invBody.innerHTML=rows.map(r=>`<tr><td><strong>${esc(r.sku)}</strong></td><td><strong>${esc(r.product_name)}</strong></td><td>${esc(r.cas_number||'—')}</td><td>${esc(r.grade||'—')}</td><td><strong>${esc(r.quantity)}</strong></td><td>${esc(r.unit)}</td><td>${esc(r.batch_no||'—')}</td><td>${esc(r.expiry_date||'—')}</td><td><button class="btn btn-soft edit-row" data-id="${r.id}">Edit</button></td></tr>`).join('');els.invBody.querySelectorAll('.edit-row').forEach(b=>b.addEventListener('click',()=>openInventory(Number(b.dataset.id))));}
  function renderPicker(){const q=els.pickerSearch.value.trim().toLowerCase();const rows=state.products.filter(p=>![p['Product Name'],p['CAS Number'],p['Product Code'],p['Grade / Traceability']].every(v=>String(v||'').toLowerCase().indexOf(q)<0)).slice(0,20);els.pickerCount.textContent=q?`${rows.length} shown`:'Search catalogue to add an item';els.picker.innerHTML=rows.map(p=>`<article class="picker-card"><h3>${esc(p['Product Name']||'Unnamed product')}</h3><div class="picker-meta"><div>CAS<b>${esc(p['CAS Number']||'—')}</b></div><div>Grade<b>${esc(p['Grade / Traceability']||'—')}</b></div><div>Code<b>${esc(p['Product Code']||'—')}</b></div></div><button class="btn btn-primary choose-product" data-index="${state.products.indexOf(p)}">Add inventory item</button></article>`).join('');els.picker.querySelectorAll('.choose-product').forEach(b=>b.addEventListener('click',()=>openNewFromProduct(state.products[Number(b.dataset.index)])));}
  function fillUnits(selected=''){els.unit.innerHTML=UNIT_OPTIONS.map(u=>`<option value="${esc(u)}" ${u===selected?'selected':''}>${esc(u)}</option>`).join('');}
  function uniqueSku(base, productKey){const clean=String(base||'').trim()||'ADDCHEM';let sku=clean;const used=new Set(state.inventory.map(x=>String(x.sku||'').toUpperCase()));let n=2;while(used.has(sku.toUpperCase())){sku=`${clean}-${n++}`;}return sku;}
  function openNewFromProduct(p){$('edit-id').value='';$('edit-product-key').value=key(p);const base=p['Product Code']||('ADDCHEM-'+String(p['Product Name']||'ITEM').toUpperCase().replace(/[^A-Z0-9]+/g,'-').slice(0,36));$('edit-sku').value=uniqueSku(base);$('edit-product-name').value=p['Product Name']||'';$('edit-cas').value=p['CAS Number']||'';$('edit-grade').value=p['Grade / Traceability']||'';$('edit-quantity').value='0';fillUnits();$('edit-batch').value='';$('edit-expiry').value='';$('edit-notes').value='';$('dialog-title').textContent='Add inventory item';$('dialog-subtitle').textContent='Grade is stored separately so the same CAS No. can have different inventory lines.';els.dialog.showModal();}
  function openInventory(id){const r=state.inventory.find(x=>Number(x.id)===id);if(!r)return;$('edit-id').value=r.id;$('edit-product-key').value=r.product_key||'';$('edit-sku').value=r.sku;$('edit-product-name').value=r.product_name;$('edit-cas').value=r.cas_number||'';$('edit-grade').value=r.grade||'';$('edit-quantity').value=r.quantity;$('edit-batch').value=r.batch_no||'';$('edit-expiry').value=r.expiry_date||'';$('edit-notes').value='';fillUnits(r.unit);$('dialog-title').textContent='Edit inventory item';$('dialog-subtitle').textContent=`${r.sku} · ${r.product_name} · ${r.grade||'No grade'}`;els.dialog.showModal();}
  function key(p){return String((p['Product Code']||p['CAS Number']||p['Product Name']||'')+'|'+(p['Grade / Traceability']||'')).toUpperCase().replace(/[^A-Z0-9._| -]+/g,'_').slice(0,180);}
  function populateBillingProducts(){const opts=state.inventory.slice().sort((a,b)=>a.product_name.localeCompare(b.product_name)||String(a.grade).localeCompare(String(b.grade))).map(r=>`<option value="${r.id}">${esc(r.sku)} · ${esc(r.product_name)} · ${esc(r.grade||'No grade')} · ${esc(r.quantity)} ${esc(r.unit)}</option>`).join('');els.billSelect.innerHTML='<option value="">Choose SKU / Grade…</option>'+opts;}
  function renderBillLines(){els.billBody.innerHTML=state.billLines.map((x,i)=>`<tr><td>${esc(x.sku)}</td><td>${esc(x.product_name)}</td><td>${esc(x.cas_number||'—')}</td><td>${esc(x.grade||'—')}</td><td>${esc(x.quantity_available)} ${esc(x.unit)}</td><td><input class="bill-line-qty" data-index="${i}" type="number" min="1" max="${x.quantity_available}" value="${x.quantity}"></td><td><button class="btn btn-soft remove-line" data-index="${i}">Remove</button></td></tr>`).join('');els.billBody.querySelectorAll('.remove-line').forEach(b=>b.addEventListener('click',()=>{state.billLines.splice(Number(b.dataset.index),1);renderBillLines();}));els.billBody.querySelectorAll('.bill-line-qty').forEach(i=>i.addEventListener('change',()=>{const idx=Number(i.dataset.index);let q=Math.floor(Number(i.value));q=Math.max(1,Math.min(state.billLines[idx].quantity_available,q));state.billLines[idx].quantity=q;i.value=q;updateBillTotal();}));updateBillTotal();}
  function updateBillTotal(){$('bill-total-units').textContent=`${state.billLines.reduce((s,x)=>s+x.quantity,0)} units`}
  document.querySelectorAll('.staff-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.staff-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(x=>x.hidden=true);btn.classList.add('active');$('tab-'+btn.dataset.tab).hidden=false;if(btn.dataset.tab==='dashboard'){loadSummary();loadBills();}if(btn.dataset.tab==='inventory'){loadInventory();}}));
  els.loginForm.addEventListener('submit',async e=>{e.preventDefault();message(els.loginMsg,'Signing in…');try{await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('email').value.trim(),password:$('password').value})});await bootstrap();}catch(err){message(els.loginMsg,err.message,'error');}});
  async function doLogout(){await api('/api/auth/logout',{method:'POST'});location.reload();}
  els.logout.addEventListener('click',doLogout);els.logoutTop.addEventListener('click',doLogout);
  $('toggle-password').addEventListener('click',()=>{const input=$('password');const show=input.type==='password';input.type=show?'text':'password';$('toggle-password').textContent=show?'Hide':'Show';$('toggle-password').setAttribute('aria-label',show?'Hide password':'Show password');});
  $('refresh-inventory').addEventListener('click',()=>loadInventory().catch(e=>message(els.invMsg,e.message,'error')));els.invSearch.addEventListener('input',renderInventory);els.pickerSearch.addEventListener('input',renderPicker);$('refresh-dashboard').addEventListener('click',loadSummary);$('refresh-bills').addEventListener('click',loadBills);$('new-inventory').addEventListener('click',()=>openNewFromProduct({'Product Name':'','Product Code':'','CAS Number':'','Grade / Traceability':''}));
  $('dialog-close').addEventListener('click',()=>els.dialog.close());$('dialog-cancel').addEventListener('click',()=>els.dialog.close());
  els.form.addEventListener('submit',async e=>{e.preventDefault();const payload={id:Number($('edit-id').value)||null,product_key:$('edit-product-key').value||null,sku:$('edit-sku').value.trim(),product_name:$('edit-product-name').value.trim(),cas_number:$('edit-cas').value.trim(),grade:$('edit-grade').value.trim(),quantity:Number($('edit-quantity').value),unit:$('edit-unit').value,batch_no:$('edit-batch').value.trim(),expiry_date:$('edit-expiry').value||null,internal_notes:$('edit-notes').value.trim(),reason:$('edit-notes').value.trim()};if(payload.id&& !payload.reason){message(els.invMsg,'Please enter a reason when correcting an existing quantity.','error');return;}try{await api('/api/inventory',{method:'POST',body:JSON.stringify(payload)});els.dialog.close();message(els.invMsg,'Inventory saved.','ok');await loadInventory();}catch(err){message(els.invMsg,err.message,'error');}});
  $('bill-add-line').addEventListener('click',()=>{const id=Number(els.billSelect.value);const row=state.inventory.find(r=>Number(r.id)===id);const qty=Math.floor(Number(els.billQty.value));if(!row||!qty||qty<1)return;if(qty>row.quantity){message(els.billingMsg,'Bill quantity cannot exceed available inventory.','error');return;}const existing=state.billLines.find(x=>x.inventory_id===id);if(existing) existing.quantity=Math.min(row.quantity,existing.quantity+qty);else state.billLines.push({...row,inventory_id:id,quantity_available:row.quantity,quantity:qty});renderBillLines();els.billQty.value=1;});
  $('save-bill').addEventListener('click',async()=>{if(!state.billLines.length){message(els.billingMsg,'Add at least one line to the bill.','error');return;}try{const d=await api('/api/bills',{method:'POST',body:JSON.stringify({customer_name:$('bill-customer').value.trim(),customer_reference:$('bill-reference').value.trim(),notes:$('bill-notes').value.trim(),items:state.billLines.map(x=>({inventory_id:x.inventory_id,quantity:x.quantity}))})});message(els.billingMsg,`Bill ${d.invoice_no} saved and inventory updated.`,'ok');state.billLines=[];renderBillLines();$('bill-customer').value='';$('bill-reference').value='';$('bill-notes').value='';await loadInventory();await loadBills();await loadSummary();}catch(err){message(els.billingMsg,err.message,'error');}});
  async function bootstrap(){const s=await me();if(!s){els.loginView.hidden=false;els.dashboard.hidden=true;els.logout.hidden=true;els.logoutTop.hidden=true;return;}state.staff=s;els.staffEmail.textContent=s.email;els.staffEmail.title=s.email;els.staffAvatar.textContent=String(s.email||'S').charAt(0).toUpperCase();$('nav-staff-state').hidden=false;els.loginView.hidden=true;els.dashboard.hidden=false;els.logout.hidden=false;els.logoutTop.hidden=false;await loadProducts();await loadInventory();await loadBills();await loadSummary();}
  bootstrap().catch(e=>message(els.loginMsg,e.message,'error'));
})();
