(function(){'use strict';
const UNIT_OPTIONS=['Bottle','Packet','Box','Vial','Tube','Ampoule','Can','Bag','Drum','Piece','Set','Other'];
const $=id=>document.getElementById(id); const state={inventory:[],products:[],customers:[],catalogue:[],billLines:[],staff:null,savedInvoice:null,editingCatalogue:null};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function msg(el,text,type=''){el.textContent=text||'';el.hidden=!text;el.className='staff-message'+(type?' '+type:'')}
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'content-type':'application/json',...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d}
async function me(){try{return(await api('/api/auth/me')).staff}catch{return null}}
async function loadProducts(){if(state.products.length)return;const r=await fetch('data/products.json',{cache:'no-store'});state.products=await r.json()}
async function loadInventory(){const q=$('inventory-search').value.trim();const d=await api('/api/inventory'+(q?'?q='+encodeURIComponent(q):''));state.inventory=d.items||[];renderInventory();populateBillProducts();}
async function loadCatalogue(){const [base,d]=await Promise.all([fetch('data/products.json',{cache:'no-store'}).then(r=>r.json()),api('/api/catalogue')]);const changes=d.items||[];const byCode=new Map(changes.map(x=>[String(x.product_code).toLowerCase(),x]));state.catalogue=base.map(p=>{const code=String(p['Product Code']||'').toLowerCase(),o=byCode.get(code);return o?{product_code:o.product_code,section:o.section||p.Section,product_name:o.product_name||p['Product Name'],description:o.description||p['Chemical Name / Description'],cas_number:o.cas_number||p['CAS Number'],grade:o.grade||p['Grade / Traceability'],pack_size:o.pack_size||p['Pack Size'],hsn_code:o.hsn_code||p['HSN Code'],gst_percent:o.gst_percent||p['GST %']||'18',notes:o.notes||p['Other / Notes'],is_deleted:!!o.is_deleted,_override:true}: {product_code:p['Product Code']||'',section:p.Section||'',product_name:p['Product Name']||'',description:p['Chemical Name / Description']||'',cas_number:p['CAS Number']||'',grade:p['Grade / Traceability']||'',pack_size:p['Pack Size']||'',hsn_code:p['HSN Code']||'',gst_percent:p['GST %']||'18',notes:p['Other / Notes']||'',is_deleted:false,_override:false}});const baseCodes=new Set(state.catalogue.map(x=>String(x.product_code).toLowerCase()));changes.filter(o=>!o.is_deleted&&!baseCodes.has(String(o.product_code).toLowerCase())).forEach(o=>state.catalogue.push({...o,_override:true}));renderCatalogue()}
async function loadCustomers(){const d=await api('/api/customers');state.customers=d.customers||[];renderCustomers();populateCustomerSelects();$('metric-customers').textContent=state.customers.length.toLocaleString('en-IN')}
async function loadBills(){const d=await api('/api/bills/recent');$('recent-bills-body').innerHTML=(d.bills||[]).map(b=>`<tr><td><strong>${esc(b.invoice_no)}</strong></td><td>${esc(b.customer_name||'—')}</td><td>${money(b.total_amount)}</td><td>${dateTime(b.created_at)}</td></tr>`).join('')||'<tr><td colspan="4">No invoices yet.</td></tr>'}
async function loadSummary(){const d=await api('/api/summary');$('metric-skus').textContent=Number(d.summary.skus).toLocaleString('en-IN');$('metric-total').textContent=Number(d.summary.totalUnits).toLocaleString('en-IN')}
function money(n){return '₹'+Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})} function dateTime(s){return new Date(String(s).replace(' ','T')+'Z').toLocaleString('en-IN')}
function renderInventory(){const q=$('inventory-search').value.trim().toLowerCase();const rows=state.inventory.filter(r=>!q||[r.sku,r.product_name,r.cas_number,r.grade].join(' ').toLowerCase().includes(q));$('inventory-table-body').innerHTML=rows.map(r=>`<tr><td><strong>${esc(r.sku)}</strong></td><td><strong>${esc(r.product_name)}</strong></td><td>${esc(r.cas_number||'—')}</td><td>${esc(r.grade||'—')}</td><td><strong>${esc(r.quantity)}</strong></td><td>${esc(r.unit)}</td><td>${esc(r.batch_no||'—')}</td><td>${esc(r.expiry_date||'—')}</td><td><button class="btn btn-soft edit-row" data-id="${r.id}">Edit</button></td></tr>`).join('');$('inventory-empty').hidden=rows.length>0;$('inventory-table-body').querySelectorAll('.edit-row').forEach(b=>b.onclick=()=>openInventory(+b.dataset.id))}
function fillUnits(selected=''){ $('edit-unit').innerHTML=UNIT_OPTIONS.map(u=>`<option ${u===selected?'selected':''}>${u}</option>`).join('') }
function key(p){return String((p['Product Code']||p['CAS Number']||p['Product Name']||'')+'|'+(p['Grade / Traceability']||'')).toUpperCase().replace(/[^A-Z0-9._| -]+/g,'_').slice(0,180)}
function openNew(p){$('edit-id').value='';$('edit-product-key').value=key(p);$('edit-sku').value=p['Product Code']||'';$('edit-product-name').value=p['Product Name']||'';$('edit-cas').value=p['CAS Number']||'';$('edit-hsn').value=p['HSN Code']||'';$('edit-grade').value=p['Grade / Traceability']||'';$('edit-quantity').value=0;fillUnits();$('edit-batch').value='';$('edit-expiry').value='';$('edit-notes').value='';$('dialog-title').textContent='Add inventory';$('inventory-dialog').showModal()}
function openInventory(id){const r=state.inventory.find(x=>+x.id===id);if(!r)return;$('edit-id').value=r.id;$('edit-product-key').value=r.product_key||'';$('edit-sku').value=r.sku;$('edit-product-name').value=r.product_name;$('edit-cas').value=r.cas_number||'';$('edit-hsn').value=r.hsn_code||'';$('edit-grade').value=r.grade||'';$('edit-quantity').value=r.quantity;fillUnits(r.unit);$('edit-batch').value=r.batch_no||'';$('edit-expiry').value=r.expiry_date||'';$('edit-notes').value='';$('dialog-title').textContent='Edit inventory';$('inventory-dialog').showModal()}
function populateBillProducts(){$('bill-product-select').innerHTML='<option value="">Choose inventory item…</option>'+state.inventory.filter(r=>+r.quantity>0).map(r=>`<option value="${r.id}">${esc(r.sku)} · ${esc(r.product_name)} · ${esc(r.grade||'No grade')} · ${r.quantity} ${esc(r.unit)}</option>`).join('')}
function populateCustomerSelects(){const opts=state.customers.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');$('bill-customer-select').innerHTML='<option value="">Select customer…</option>'+opts;$('bill-ship-select').innerHTML='<option value="">Same as Bill To</option>'+opts}
function renderCatalogue(){const q=($('catalogue-search')?.value||'').trim().toLowerCase();const rows=state.catalogue.filter(r=>!q||[r.product_code,r.product_name,r.cas_number,r.hsn_code,r.grade,r.section].join(' ').toLowerCase().includes(q));$('catalogue-body').innerHTML=rows.map(r=>`<tr><td><strong>${esc(r.product_code)}</strong></td><td><strong>${esc(r.product_name)}</strong><small>${esc(r.section||'')}</small></td><td>${esc(r.cas_number||'—')}</td><td>${esc(r.grade||'—')}</td><td>${esc(r.pack_size||'—')}</td><td>${esc(r.hsn_code||'—')}</td><td>${esc(r.gst_percent||'18')}%</td><td>${r.is_deleted?'Removed':'Active'}</td><td><button class="btn btn-soft edit-catalogue" data-code="${esc(r.product_code)}">Edit</button></td></tr>`).join('');$('catalogue-empty').hidden=rows.length>0} 
function openCatalogue(c=null){state.editingCatalogue=c;$('cat-code').value=c?.product_code||'';$('cat-section').value=c?.section||'';$('cat-name').value=c?.product_name||'';$('cat-description').value=c?.description||'';$('cat-cas').value=c?.cas_number||'';$('cat-grade').value=c?.grade||'';$('cat-pack').value=c?.pack_size||'';$('cat-hsn').value=c?.hsn_code||'';$('cat-gst').value=c?.gst_percent||'18';$('cat-notes').value=c?.notes||'';$('catalogue-title').textContent=c?'Edit catalogue product':'Add catalogue product';$('catalogue-delete').hidden=!c;$('catalogue-dialog').showModal()} 
async function saveCatalogue(e){e.preventDefault();const payload={product_code:$('cat-code').value.trim(),section:$('cat-section').value.trim(),product_name:$('cat-name').value.trim(),description:$('cat-description').value.trim(),cas_number:$('cat-cas').value.trim(),grade:$('cat-grade').value.trim(),pack_size:$('cat-pack').value.trim(),hsn_code:$('cat-hsn').value.trim(),gst_percent:$('cat-gst').value,notes:$('cat-notes').value.trim()};try{await api('/api/catalogue',{method:'POST',body:JSON.stringify(payload)});$('catalogue-dialog').close();msg($('catalogue-message'),'Catalogue product saved.','ok');await loadCatalogue()}catch(err){msg($('catalogue-message'),err.message,'error')}} 
async function deleteCatalogue(){const c=state.editingCatalogue;if(!c)return; if(!confirm(`Remove ${c.product_name} from the public catalogue?`))return;try{await api('/api/catalogue/delete',{method:'POST',body:JSON.stringify({product_code:c.product_code})});$('catalogue-dialog').close();msg($('catalogue-message'),'Product removed from the public catalogue.','ok');await loadCatalogue()}catch(err){msg($('catalogue-message'),err.message,'error')}} 
function renderCustomers(){$('customers-body').innerHTML=state.customers.map(c=>`<tr><td><strong>${esc(c.name)}</strong>${c.contact_name?`<small>${esc(c.contact_name)}</small>`:''}</td><td>${esc(c.phone||'—')}</td><td>${esc([c.address,c.city,c.state,c.pin].filter(Boolean).join(', ')||'—')}</td><td>${esc(c.gstin||'—')}</td><td><button class="btn btn-soft edit-customer" data-id="${c.id}">Edit</button></td></tr>`).join('');$('customers-empty').hidden=state.customers.length>0;$('customers-body').querySelectorAll('.edit-customer').forEach(b=>b.onclick=()=>openCustomer(+b.dataset.id))}
function customer(id){return state.customers.find(c=>+c.id===+id)}
function showCustomer(){const c=customer($('bill-customer-select').value);const box=$('selected-customer-card');if(!c){box.hidden=true;box.innerHTML='';return}box.hidden=false;box.innerHTML=`<strong>${esc(c.name)}</strong><br>${esc([c.address,c.city,c.state,c.pin].filter(Boolean).join(', '))}${c.gstin?`<br>GSTIN: ${esc(c.gstin)}`:''}`}
function addLine(){const row=state.inventory.find(r=>+r.id===+$('bill-product-select').value);const qty=Math.floor(+$('bill-qty').value);const rate=+$('bill-rate').value;if(!row||qty<1||rate<0||!Number.isFinite(rate))return msg($('billing-message'),'Select an item and enter a valid quantity and rate.','error');if(qty>+row.quantity)return msg($('billing-message'),'Quantity exceeds available stock.','error');const existing=state.billLines.find(x=>+x.inventory_id===+row.id);if(existing){existing.quantity=Math.min(+row.quantity,existing.quantity+qty);existing.rate=rate}else state.billLines.push({...row,inventory_id:+row.id,quantity:qty,rate});$('bill-qty').value=1;$('bill-rate').value='';renderLines()}
function renderLines(){$('bill-lines-body').innerHTML=state.billLines.map((x,i)=>{const base=x.quantity*x.rate,cgst=base*.09,sgst=base*.09;return `<tr><td>${i+1}</td><td><strong>${esc(x.product_name)}</strong><small>${esc(x.sku)}${x.batch_no?` · Batch ${esc(x.batch_no)}`:''}</small></td><td>${esc(x.hsn_code||'—')}</td><td><input data-i="${i}" class="line-qty" type="number" min="1" max="${x.quantity_available||x.quantity}" value="${x.quantity}"><small>${esc(x.unit)}</small></td><td><input data-i="${i}" class="line-rate" type="number" min="0" step="0.01" value="${x.rate.toFixed(2)}"></td><td>${money(cgst)}</td><td>${money(sgst)}</td><td>${money(base)}</td><td><button class="btn btn-soft remove-line" data-i="${i}">×</button></td></tr>`}).join('')||'<tr><td colspan="9" class="empty-cell">Add products to build the invoice.</td></tr>';document.querySelectorAll('.remove-line').forEach(b=>b.onclick=()=>{state.billLines.splice(+b.dataset.i,1);renderLines()});document.querySelectorAll('.line-qty').forEach(i=>i.onchange=()=>{const x=state.billLines[+i.dataset.i];x.quantity=Math.max(1,Math.min(+(x.quantity_available||999999),Math.floor(+i.value)||1));renderLines()});document.querySelectorAll('.line-rate').forEach(i=>i.onchange=()=>{state.billLines[+i.dataset.i].rate=Math.max(0,+i.value||0);renderLines()});updateTotals();renderPreview()}
function totals(){const subtotal=state.billLines.reduce((s,x)=>s+x.quantity*x.rate,0);return{subtotal,cgst:subtotal*.09,sgst:subtotal*.09,total:subtotal*1.18}}
function updateTotals(){const t=totals();$('bill-subtotal').textContent=money(t.subtotal);$('bill-cgst').textContent=money(t.cgst);$('bill-sgst').textContent=money(t.sgst);$('bill-grand').textContent=money(t.total);$('bill-balance').textContent=money(t.total);$('bill-total-units').textContent=state.billLines.reduce((s,x)=>s+x.quantity,0)+' units'}
function nextInvoice(){const d=new Date();return `INV/${String(d.getFullYear()).slice(2)}-${String(d.getFullYear()+1).slice(2)}/`+(Math.floor(Math.random()*9000)+1000)}
function setDates(){const d=new Date();const iso=d.toISOString().slice(0,10);$('bill-date').value=iso;const due=new Date(d);due.setDate(due.getDate()+60);$('bill-due').value=due.toISOString().slice(0,10);$('bill-invoice').value=nextInvoice()}
function words(n){n=Math.round(n);if(n===0)return'Zero';const ones=['','One','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Eleven','Twelve','Thirteen','Fourteen','Fifteen','Sixteen','Seventeen','Eighteen','Nineteen'];const tens=['','','Twenty','Thirty','Forty','Fifty','Sixty','Seventy','Eighty','Ninety'];function chunk(x){if(x<20)return ones[x];if(x<100)return tens[Math.floor(x/10)]+' '+ones[x%10];return ones[Math.floor(x/100)]+' Hundred'+(x%100?' '+chunk(x%100):'')}let out='';const cr=Math.floor(n/10000000);n%=10000000;const la=Math.floor(n/100000);n%=100000;const th=Math.floor(n/1000);n%=1000;if(cr)out+=chunk(cr)+' Crore ';if(la)out+=chunk(la)+' Lakh ';if(th)out+=chunk(th)+' Thousand ';if(n)out+=chunk(n);return out.trim()+' Only'}
function renderPreview(){const c=customer($('bill-customer-select').value), ship=customer($('bill-ship-select').value)||c,t=totals();const date=$('bill-date').value?new Date($('bill-date').value+'T00:00:00').toLocaleDateString('en-GB'):'';const due=$('bill-due').value?new Date($('bill-due').value+'T00:00:00').toLocaleDateString('en-GB'):'';const rows=state.billLines.map((x,i)=>{const base=x.quantity*x.rate;return `<tr><td>${i+1}</td><td><b>${esc(x.product_name)}</b><br><span class="small">${esc(x.sku)}${x.batch_no?`<br>${esc(x.batch_no)}`:''}</span></td><td>${esc(x.hsn_code||'—')}</td><td>${x.quantity}<br>${esc(x.unit)}</td><td>${money(x.rate)}</td><td>9%<br>${money(base*.09)}</td><td>9%<br>${money(base*.09)}</td><td>${money(base)}</td></tr>`}).join('');$('invoice-preview').innerHTML=`<div class="inv-top"><div><div class="company">ADDCHEM Enterprises</div><div>Survey.No.124, Flat.No - 506, Sri Ram Residency<br>Kompally (V) Qutbullapur. Ph: 8919580575<br>Hyderabad Telangana 500014<br>GSTIN 36ABJFA2471K1ZA<br>UDYAM-TS-20-0031111</div></div><div class="inv-title">TAX INVOICE</div></div><div class="meta-grid"><div class="meta-cell"><b>Invoice No. :</b> ${esc($('bill-invoice').value)}<br><b>Invoice Date :</b> ${date}<br><b>Terms :</b> ${esc($('bill-terms').value)}<br><b>Due Date :</b> ${due}<br><b>P.O.# :</b> ${esc($('bill-po').value)}</div><div class="meta-cell"><b>Place Of Supply :</b> ${esc($('bill-place').value)}</div></div><div class="billto"><div><b>BILL TO</b><br><br>${c?`<b>${esc(c.name)}</b><br>${esc([c.address,c.city,c.pin,c.state,'India'].filter(Boolean).join(', '))}${c.gstin?`<br>GSTIN ${esc(c.gstin)}`:''}`:'Select a customer'}</div><div><b>SHIP TO</b><br><br>${ship?`<b>${esc(ship.name)}</b><br>${esc([ship.address,ship.city,ship.pin,ship.state,'India'].filter(Boolean).join(', '))}${ship.gstin?`<br>GSTIN ${esc(ship.gstin)}`:''}`:'Same as Bill To'}</div></div><table><thead><tr><th>#</th><th>Item & Description</th><th>HSN/SAC</th><th>Qty</th><th>Rate</th><th>CGST<br>% / Amt</th><th>SGST<br>% / Amt</th><th>Amount</th></tr></thead><tbody>${rows||'<tr><td colspan="8" style="text-align:center">No items</td></tr>'}</tbody></table><div class="summary-row"><div class="words"><b>Total in Words</b><br><i>Indian Rupee ${words(t.total)}</i><br><br><b>Notes</b><br>${esc($('bill-notes').value||'Thanks for your business.')}</div><div class="totals"><div><span>Sub Total</span><b>${money(t.subtotal)}</b></div><div><span>CGST9 (9%)</span><b>${money(t.cgst)}</b></div><div><span>SGST9 (9%)</span><b>${money(t.sgst)}</b></div><div class="grand"><span>Total</span><b>${money(t.total)}</b></div><div><span>Balance Due</span><b>${money(t.total)}</b></div><div class="signature"><br>Authorized Signature</div></div></div>`}
function formCustomer(c={}){$('customer-id').value=c.id||'';$('customer-name').value=c.name||'';$('customer-contact').value=c.contact_name||'';$('customer-gstin').value=c.gstin||'';$('customer-phone').value=c.phone||'';$('customer-address').value=c.address||'';$('customer-city').value=c.city||'';$('customer-state').value=c.state||'';$('customer-pin').value=c.pin||'';$('customer-notes').value=c.notes||'';$('customer-title').textContent=c.id?'Edit customer':'Add customer';$('customer-dialog').showModal()}
function openCustomer(id){formCustomer(customer(id))}
async function saveCustomer(e){e.preventDefault();const payload={id:+$('customer-id').value||null,name:$('customer-name').value.trim(),contact_name:$('customer-contact').value.trim(),gstin:$('customer-gstin').value.trim(),phone:$('customer-phone').value.trim(),address:$('customer-address').value.trim(),city:$('customer-city').value.trim(),state:$('customer-state').value.trim(),pin:$('customer-pin').value.trim(),notes:$('customer-notes').value.trim()};try{await api('/api/customers',{method:'POST',body:JSON.stringify(payload)});$('customer-dialog').close();msg($('customer-message'),'Customer saved.','ok');await loadCustomers()}catch(err){msg($('customer-message'),err.message,'error')}}
async function saveInventory(e){e.preventDefault();const id=+$('edit-id').value||null;const payload={id,product_key:$('edit-product-key').value||null,sku:$('edit-sku').value.trim(),product_name:$('edit-product-name').value.trim(),cas_number:$('edit-cas').value.trim(),hsn_code:$('edit-hsn').value.trim(),grade:$('edit-grade').value.trim(),quantity:+$('edit-quantity').value,unit:$('edit-unit').value,batch_no:$('edit-batch').value.trim(),expiry_date:$('edit-expiry').value||null,internal_notes:$('edit-notes').value.trim(),reason:$('edit-notes').value.trim()};if(id&&!payload.reason)return msg($('inventory-message'),'Enter a note when correcting an existing quantity.','error');try{await api('/api/inventory',{method:'POST',body:JSON.stringify(payload)});$('inventory-dialog').close();msg($('inventory-message'),'Inventory saved.','ok');await loadInventory();await loadSummary()}catch(err){msg($('inventory-message'),err.message,'error')}}
async function saveBill(){if(!state.billLines.length)return msg($('billing-message'),'Add at least one product.','error');const c=customer($('bill-customer-select').value);if(!c)return msg($('billing-message'),'Select a customer.','error');const t=totals();const payload={invoice_no:$('bill-invoice').value.trim(),invoice_date:$('bill-date').value,terms:$('bill-terms').value.trim(),due_date:$('bill-due').value,po_number:$('bill-po').value.trim(),place_of_supply:$('bill-place').value.trim(),customer_id:c.id,ship_customer_id:+$('bill-ship-select').value||c.id,notes:$('bill-notes').value.trim(),subtotal:t.subtotal,cgst:t.cgst,sgst:t.sgst,total_amount:t.total,items:state.billLines.map(x=>({inventory_id:x.inventory_id,quantity:x.quantity,rate:x.rate}))};try{const d=await api('/api/bills',{method:'POST',body:JSON.stringify(payload)});state.savedInvoice=d.invoice_no;msg($('billing-message'),`Invoice ${d.invoice_no} saved and stock deducted.`,'ok');await loadInventory();await loadBills();await loadSummary();renderPreview()}catch(err){msg($('billing-message'),err.message,'error')}}
function downloadPdf(){renderPreview();const jsPDF=window.jspdf?.jsPDF;if(!jsPDF)return msg($('billing-message'),'PDF library could not load. Please refresh the page.','error');const doc=new jsPDF({unit:'mm',format:'a4'});doc.html($('invoice-preview'),{x:8,y:8,width:194,windowWidth:850,margin:[0,0,0,0],autoPaging:'text',callback:d=>d.save((($('bill-invoice').value||'ADDCHEM-Invoice').replace(/[^a-z0-9_-]/gi,'_'))+'.pdf')});}
function switchTab(tab){document.querySelectorAll('.staff-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.tab-panel').forEach(p=>p.hidden=p.id!=='tab-'+tab);if(tab==='inventory')loadInventory();if(tab==='customers')loadCustomers();if(tab==='dashboard'){loadSummary();loadBills();loadCustomers()}if(tab==='billing'){loadInventory();loadCustomers();renderLines()}if(tab==='settings'){loadCatalogue()}}
document.querySelectorAll('.staff-tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$('login-form').onsubmit=async e=>{e.preventDefault();msg($('login-message'),'Signing in…');try{await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('email').value.trim(),password:$('password').value})});await bootstrap()}catch(err){msg($('login-message'),err.message,'error')}};
async function logout(){await api('/api/auth/logout',{method:'POST'});location.reload()}$('logout').onclick=logout;$('logout-top').onclick=logout;$('inventory-search').oninput=renderInventory;$('refresh-inventory').onclick=()=>loadInventory().catch(e=>msg($('inventory-message'),e.message,'error'));$('new-inventory').onclick=()=>openNew({'Product Name':'','Product Code':'','CAS Number':'','Grade / Traceability':''});$('dialog-close').onclick=()=>$('inventory-dialog').close();$('dialog-cancel').onclick=()=>$('inventory-dialog').close();$('inventory-form').onsubmit=saveInventory;$('bill-add-line').onclick=addLine;$('bill-customer-select').onchange=()=>{showCustomer();renderPreview()};$('bill-ship-select').onchange=renderPreview;$('new-customer').onclick=()=>formCustomer();$('add-customer-inline').onclick=()=>formCustomer();$('customer-close').onclick=()=>$('customer-dialog').close();$('customer-cancel').onclick=()=>$('customer-dialog').close();$('customer-form').onsubmit=saveCustomer;$('save-bill').onclick=saveBill;$('download-pdf').onclick=downloadPdf;$('preview-bill').onclick=()=>{renderPreview();$('invoice-preview-wrap').scrollIntoView({behavior:'smooth',block:'nearest'})};$('close-preview').onclick=()=>{$('invoice-preview-wrap').style.display='none'};document.querySelectorAll('#tab-billing input,#tab-billing textarea').forEach(el=>el.addEventListener('input',renderPreview));$('refresh-bills').onclick=loadBills;$('new-catalogue').onclick=()=>openCatalogue();$('refresh-catalogue').onclick=()=>loadCatalogue().catch(e=>msg($('catalogue-message'),e.message,'error'));$('catalogue-search').oninput=renderCatalogue;$('catalogue-close').onclick=()=>$('catalogue-dialog').close();$('catalogue-cancel').onclick=()=>$('catalogue-dialog').close();$('catalogue-form').onsubmit=saveCatalogue;$('catalogue-delete').onclick=deleteCatalogue;$('catalogue-body').onclick=e=>{const b=e.target.closest('.edit-catalogue');if(b)openCatalogue(state.catalogue.find(x=>x.product_code===b.dataset.code))};
async function bootstrap(){const s=await me();if(!s){$('login-view').hidden=false;$('dashboard-view').hidden=true;$('logout').hidden=true;$('logout-top').hidden=true;return}state.staff=s;$('staff-email').textContent=s.email;$('login-view').hidden=true;$('dashboard-view').hidden=false;$('logout').hidden=false;$('logout-top').hidden=false;setDates();await loadProducts();await loadInventory();await loadCustomers();await loadCatalogue();await loadBills();await loadSummary();renderLines()}bootstrap().catch(e=>msg($('login-message'),e.message,'error'));
})();
